### ISSUE TITLE
FabricMonitoring_TenantSettings_TransformData - Notebook

### ISSUE THREAD

**Issue by GilbertQue** [tomatminceddata/FabricMonitoring#1]
The default setting has got the Lakehouse hard-coded.

It requires changing the variable for the theLakehouse = "theLakeHouse"

I would suggest in the documentation this is highlighted to be changed to the lakehouse that has been created in the tenant?

**Comment by tomatminceddata** [comment]
Hey @GilbertQue , thank you very much for pointing this out. I changed the cell 2, so that the values of the variables 

- theLakehouse and
- deltaTablePrefix

configured in the  FabricMonitoring_Variables.json are used.

The code now looks like this:
`theLakehouse = df.first()['theLakehouse']`
`deltaTablePrefix = df.first()['deltaTablePrefix']`

**Comment by tomatminceddata** [comment]
Fixed the first issue.
